/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CheckkerEscrow {
  export type GameStruct = {
    gameId: BytesLike;
    white: AddressLike;
    black: AddressLike;
    betAmount: BigNumberish;
    whiteDeposit: BigNumberish;
    blackDeposit: BigNumberish;
    status: BigNumberish;
    winner: AddressLike;
    createdAt: BigNumberish;
  };

  export type GameStructOutput = [
    gameId: string,
    white: string,
    black: string,
    betAmount: bigint,
    whiteDeposit: bigint,
    blackDeposit: bigint,
    status: bigint,
    winner: string,
    createdAt: bigint
  ] & {
    gameId: string;
    white: string;
    black: string;
    betAmount: bigint;
    whiteDeposit: bigint;
    blackDeposit: bigint;
    status: bigint;
    winner: string;
    createdAt: bigint;
  };
}

export interface CheckkerEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelGame"
      | "createGame"
      | "deposit"
      | "games"
      | "getGame"
      | "getGameStatus"
      | "houseCutBps"
      | "houseWallet"
      | "isGameReady"
      | "owner"
      | "referee"
      | "renounceOwnership"
      | "reportDraw"
      | "reportWinner"
      | "setHouseCutBps"
      | "setHouseWallet"
      | "setReferee"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositMade"
      | "GameCancelled"
      | "GameCreated"
      | "GameDrawn"
      | "GameResolved"
      | "GameStarted"
      | "OwnershipTransferred"
      | "RefundIssued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelGame",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "games", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getGame", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getGameStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "houseCutBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "houseWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isGameReady",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "referee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportDraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportWinner",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setHouseCutBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHouseWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "cancelGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseCutBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGameReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "referee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reportDraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHouseCutBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHouseWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setReferee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DepositMadeEvent {
  export type InputTuple = [
    gameId: BytesLike,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: string, player: string, amount: bigint];
  export interface OutputObject {
    gameId: string;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCancelledEvent {
  export type InputTuple = [gameId: BytesLike];
  export type OutputTuple = [gameId: string];
  export interface OutputObject {
    gameId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCreatedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    white: AddressLike,
    black: AddressLike,
    betAmount: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    white: string,
    black: string,
    betAmount: bigint
  ];
  export interface OutputObject {
    gameId: string;
    white: string;
    black: string;
    betAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameDrawnEvent {
  export type InputTuple = [gameId: BytesLike, refundEach: BigNumberish];
  export type OutputTuple = [gameId: string, refundEach: bigint];
  export interface OutputObject {
    gameId: string;
    refundEach: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameResolvedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    winner: AddressLike,
    payout: BigNumberish,
    houseCut: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    winner: string,
    payout: bigint,
    houseCut: bigint
  ];
  export interface OutputObject {
    gameId: string;
    winner: string;
    payout: bigint;
    houseCut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStartedEvent {
  export type InputTuple = [gameId: BytesLike];
  export type OutputTuple = [gameId: string];
  export interface OutputObject {
    gameId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: string, player: string, amount: bigint];
  export interface OutputObject {
    gameId: string;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CheckkerEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): CheckkerEscrow;
  waitForDeployment(): Promise<this>;

  interface: CheckkerEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelGame: TypedContractMethod<[_gameId: BytesLike], [void], "nonpayable">;

  createGame: TypedContractMethod<
    [
      _gameId: BytesLike,
      _white: AddressLike,
      _black: AddressLike,
      _betAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[_gameId: BytesLike], [void], "payable">;

  games: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        gameId: string;
        white: string;
        black: string;
        betAmount: bigint;
        whiteDeposit: bigint;
        blackDeposit: bigint;
        status: bigint;
        winner: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getGame: TypedContractMethod<
    [_gameId: BytesLike],
    [CheckkerEscrow.GameStructOutput],
    "view"
  >;

  getGameStatus: TypedContractMethod<[_gameId: BytesLike], [bigint], "view">;

  houseCutBps: TypedContractMethod<[], [bigint], "view">;

  houseWallet: TypedContractMethod<[], [string], "view">;

  isGameReady: TypedContractMethod<[_gameId: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  referee: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reportDraw: TypedContractMethod<[_gameId: BytesLike], [void], "nonpayable">;

  reportWinner: TypedContractMethod<
    [_gameId: BytesLike, _winner: AddressLike],
    [void],
    "nonpayable"
  >;

  setHouseCutBps: TypedContractMethod<
    [_bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHouseWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setReferee: TypedContractMethod<
    [_referee: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelGame"
  ): TypedContractMethod<[_gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [
      _gameId: BytesLike,
      _white: AddressLike,
      _black: AddressLike,
      _betAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[_gameId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        gameId: string;
        white: string;
        black: string;
        betAmount: bigint;
        whiteDeposit: bigint;
        blackDeposit: bigint;
        status: bigint;
        winner: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [_gameId: BytesLike],
    [CheckkerEscrow.GameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGameStatus"
  ): TypedContractMethod<[_gameId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "houseCutBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "houseWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isGameReady"
  ): TypedContractMethod<[_gameId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referee"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportDraw"
  ): TypedContractMethod<[_gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportWinner"
  ): TypedContractMethod<
    [_gameId: BytesLike, _winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHouseCutBps"
  ): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHouseWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferee"
  ): TypedContractMethod<[_referee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DepositMade"
  ): TypedContractEvent<
    DepositMadeEvent.InputTuple,
    DepositMadeEvent.OutputTuple,
    DepositMadeEvent.OutputObject
  >;
  getEvent(
    key: "GameCancelled"
  ): TypedContractEvent<
    GameCancelledEvent.InputTuple,
    GameCancelledEvent.OutputTuple,
    GameCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameDrawn"
  ): TypedContractEvent<
    GameDrawnEvent.InputTuple,
    GameDrawnEvent.OutputTuple,
    GameDrawnEvent.OutputObject
  >;
  getEvent(
    key: "GameResolved"
  ): TypedContractEvent<
    GameResolvedEvent.InputTuple,
    GameResolvedEvent.OutputTuple,
    GameResolvedEvent.OutputObject
  >;
  getEvent(
    key: "GameStarted"
  ): TypedContractEvent<
    GameStartedEvent.InputTuple,
    GameStartedEvent.OutputTuple,
    GameStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;

  filters: {
    "DepositMade(bytes32,address,uint256)": TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;
    DepositMade: TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;

    "GameCancelled(bytes32)": TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;
    GameCancelled: TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;

    "GameCreated(bytes32,address,address,uint256)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameDrawn(bytes32,uint256)": TypedContractEvent<
      GameDrawnEvent.InputTuple,
      GameDrawnEvent.OutputTuple,
      GameDrawnEvent.OutputObject
    >;
    GameDrawn: TypedContractEvent<
      GameDrawnEvent.InputTuple,
      GameDrawnEvent.OutputTuple,
      GameDrawnEvent.OutputObject
    >;

    "GameResolved(bytes32,address,uint256,uint256)": TypedContractEvent<
      GameResolvedEvent.InputTuple,
      GameResolvedEvent.OutputTuple,
      GameResolvedEvent.OutputObject
    >;
    GameResolved: TypedContractEvent<
      GameResolvedEvent.InputTuple,
      GameResolvedEvent.OutputTuple,
      GameResolvedEvent.OutputObject
    >;

    "GameStarted(bytes32)": TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;
    GameStarted: TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RefundIssued(bytes32,address,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
  };
}
