import 'package:flutter/material.dart';

/// Maps string icon names to Material Icons.
IconData appIcon(String name) => switch (name) {
      'game-controller' => Icons.sports_esports,
      'trophy' => Icons.emoji_events,
      'people' => Icons.people,
      'school' => Icons.school,
      'extension-puzzle' => Icons.extension,
      'eye' => Icons.visibility,
      'wifi' => Icons.wifi,
      'flash' => Icons.flash_on,
      'stats-chart' => Icons.bar_chart,
      'person' => Icons.person,
      'settings' => Icons.settings,
      'home' => Icons.home,
      'arrow-back' => Icons.arrow_back,
      'close' => Icons.close,
      'send' => Icons.send,
      'chatbubble' => Icons.chat_bubble,
      'time' => Icons.access_time,
      'checkmark' => Icons.check,
      'star' => Icons.star,
      'heart' => Icons.favorite,
      'skull' => Icons.dangerous,
      'flag' => Icons.flag,
      'copy' => Icons.copy,
      'book' => Icons.menu_book,
      'bulb' => Icons.lightbulb,
      'lock-closed' => Icons.lock,
      'lock-open' => Icons.lock_open,
      'information-circle' => Icons.info,
      'help-circle' => Icons.help,
      'refresh' => Icons.refresh,
      'play' => Icons.play_arrow,
      'pause' => Icons.pause,
      'skip-forward' => Icons.skip_next,
      'skip-backward' => Icons.skip_previous,
      'menu' => Icons.menu,
      'chevron-forward' => Icons.chevron_right,
      'chevron-back' => Icons.chevron_left,
      'wallet' => Icons.account_balance_wallet,
      'diamond' => Icons.diamond,
      'dice' => Icons.casino,
      _ => Icons.help_outline,
    };
