import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// Background music service: loops the ambient `bgm.wav` pad generated by
/// `tool/generate_sounds.dart`. Singleton, mirroring [SoundService].
class MusicService {
  static final MusicService _instance = MusicService._internal();
  factory MusicService() => _instance;
  MusicService._internal();

  AudioPlayer? _player;
  bool _playing = false;

  bool get playing => _playing;

  Future<void> start({double volume = 0.5}) async {
    if (_playing) {
      await setVolume(volume);
      return;
    }
    try {
      _player ??= AudioPlayer(playerId: 'bgm_player');
      await _player!.setReleaseMode(ReleaseMode.loop);
      await _player!.setVolume(volume.clamp(0.0, 1.0));
      await _player!.play(AssetSource('sounds/bgm.wav'));
      _playing = true;
    } catch (e) {
      debugPrint('[MusicService] start failed: $e');
    }
  }

  Future<void> stop() async {
    if (!_playing) return;
    try {
      await _player?.stop();
    } catch (e) {
      debugPrint('[MusicService] stop failed: $e');
    }
    _playing = false;
  }

  Future<void> setVolume(double volume) async {
    try {
      await _player?.setVolume(volume.clamp(0.0, 1.0));
    } catch (e) {
      debugPrint('[MusicService] setVolume failed: $e');
    }
  }

  /// Apply a settings change: start, stop, or retune volume.
  Future<void> sync({required bool enabled, required double volume}) async {
    if (enabled) {
      await start(volume: volume);
    } else {
      await stop();
    }
  }

  Future<void> dispose() async {
    await stop();
    await _player?.dispose();
    _player = null;
  }
}
